# CI de Nivel 01 - Disparo manual a partir de 1 clique

# nome do nosso 'pipeline'
name: 'Yarn - Execução Manual a partir do clique - N1'

# regras de disparo, gatilhos ou triggers
# gatilho de execução manual = workflow_dispatch
on:
  workflow_dispatch:

  #tarefas que sao executadas dentro dos pipelines sao jobs
jobs:
  unity-tests:
    #maquina que o job vai executar
    runs-on: ubuntu-latest

    #passos para o script de build
    steps:
      #clone do projeto
      - uses: actions/checkout@v4

      #instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: latest

      # instalação do yarn
      - name: Instalando Yarn
        run: npm install -g yarn

      # instalando dependências
      - name: Instalando dependências
        run: yarn

      # executor de testes unitários
      - name: Executando testes unitários
        run: yarn test

    